### PR TITLE
Optimize VRML output

### PR DESCRIPTION
**Pull request by VolkerEnderlein**
This PR optimizes the VRML1 output and additionally adds VRML2 output. The VRML1 output was checkd against the latest Caligari trueSpace freely available (7.6) . See image attached.

Additionally a memory overwrite issue in Utilities.cpp was fixed. 

Truespace76WithSampleData

### CODE REVIEW

**Comment by ferrellsl** [comment]
Wow, thank you so much for all your hard work.  I wasn't expecting you to do so much work. I just tested your changes and I'm very happy with the results.  I'll update the Readme.md and put out a new release later today and I'll make sure to mention you in the Readme.md and the change log.

**Comment by VolkerEnderlein** [comment]
Can you additionally test the Outline export to VRML? I did not have any data to test that, maybe you have some more data around.

**Comment by ferrellsl** [comment]
Yes, I'll have to find some shoreline data and the corresponding LIDAR ground returns.   I don't have any shoreline data on hand either.

 

    On Sunday, June 4, 2023 at 08:00:11 AM MST, Volker Enderlein ***@***.***> wrote:  
 
 


Can you additionally test the Outline export to VRML? I did not have any data to test that, maybe you have some more data around.

**Comment by ferrellsl** [comment]
I did a quick check of the outline rendering.  I created a very poorly drawn shoreline file and opened it with QuikGrid.  You can see the red line in this pic.

image

After creating a VRML2 file I don't see the outline being rendered. gl3v throws the following error but it does render the ground model properly:

"Coin waring [indexedlineset}::GLRender(); Erroneous coordinate index: -1 {Should be within [0,17]).  Aborting rendering.  This message will be shown once, but there might be more errors"

Windows 3D Builder renders the file without any complaints but it doesn't show the redline either.

Here's the data I used for testing.


[ground_returns.txt](https://github.com/ferrellsl/QuikGrid/files/11650002/ground_returns.txt)
[shoreline.txt](https://github.com/ferrellsl/QuikGrid/files/11650005/shoreline.txt)

**Comment by ferrellsl** [comment]
gl3v is drawing the map axis in green properly

image

**Pull request merged**
